#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: `basename $0` [domain]"
    exit
fi

DIR=`realpath $(dirname $0)`
echo "========== DIG Records ============"
timeout 4 sh $DIR/scripts/dig-records.sh $1
echo "========== PORT SCAN (22,80,443) ============"
timeout 8 sh $DIR/scripts/nmap-ports.sh $1
echo "========== WHOIS expiry ============"
timeout 4 sh $DIR/scripts/whois-expiry.sh $1
echo "========== SSL Expiry ============"
timeout 4 sh $DIR/scripts/ssl-expiry.sh $1
