#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: `basename $0` [domain]"
    exit
fi

echo "========== DIG Records ============"
timeout 4 sh scripts/dig-records.sh $1
echo "========== PORT SCAN (22,80,443) ============"
timeout 8 sh scripts/nmap-ports.sh $1
echo "========== WHOIS expiry ============"
timeout 4 sh scripts/whois-expiry.sh $1
echo "========== SSL Expiry ============"
timeout 4 sh scripts/ssl-expiry.sh $1
echo "========== SSL certificate days left ============"
timeout 4 sh scripts/ssl-expiry.sh $1 | python scripts/ssl-expiry-to-days.py
echo "========== WHOIS days left ============"
timeout 4 sh scripts/whois-expiry.sh redbyte.co | python scripts/whois-expiry-to-days.py
